- name: Deploy container on remote server
  hosts: vm_host
  tasks:
    - name: Create workdir
      file:
        path: '{{ workdir }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: Create Docker Compose file
      template:
        dest: '{{ workdir }}/docker-compose.yml'
        src: '../docker-compose.yml'
        mode: 0755
      tags: [ 'prepare' ]

    - name: Create run script
      template:
        dest: '{{ workdir }}/run.sh'
        src: 'templates/run.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: run new docker container
      command: '{{ workdir }}/run.sh'
      tags: [ 'deploy' ]
